version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: billing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: billing
    ports:
      - "5432:5432"
    volumes:
      - billing-data:/var/lib/postgresql/data
    restart: always

  api:
    image: billing-app:v1
    container_name: billing-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/billing?sslmode=disable
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: billing-redis
    ports:
      - "6379:6379"
    restart: always



volumes:
  billing-data: